console.log('test.js')
console.log("added github workflow I hope it works")
console.log("changed permissions")
console.log("adding releases")
console.log("adding another feature for v1.2.0 tadah")
console.log("adding a fix for v1.2.4 tadah")
console.log("added a fix for v1.2.5")
console.log("added a feature for v1.3.0")
console.log("added a fix for v1.3.1")