name: Release Workflow

on:
  push:
    branches:
      - master  # Change this to your main branch name

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Use the version you need

      - name: Install dependencies
        run: npm install

      - name: Bump Version and Create Release
        id: bump
        run: |
          npm install -g standard-version
          standard-version
          
      - name: Push Changes and Tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the secret name you created
        run: |
          git push --follow-tags origin main

